### PR TITLE
AR synchronization with Naver map sdk

### PR DESCRIPTION
**Pull request by Snowapril**
This revision includes:

### References
1. https://developers.google.com/ar
2. https://github.com/github/super-linter
3. https://github.com/google-ar/arcore-android-sdk
4. https://github.com/ThomasGorisse/sceneform-android-sdk

### CODE REVIEW

**Review by lijm1358 — COMMENTED** [review]
App keeps crashing after about 10 seconds of running with LogCat:
```
2021-08-06 11:31:26.482 27278-27278/com.sinbaram.mapgo E/Filament: Panic
    in HandleBase::HandleId filament::OpenGLDriver::allocateHandle(void *):348
    reason: OpenGL backend handle arena is full, please increase FILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB which is currently set to 4 MiB.
```
I know project is under development, so wonder if it's normal.

**Comment by hyunyunV** [comment]
LGTM

**Review by hyunyunV — APPROVED** [review]
LGTM

**Review by hyunyunV — APPROVED** [review]

**Comment by Snowapril** [comment]
> App keeps crashing after about 10 seconds of running with LogCat:
> 
> ```
> 2021-08-06 11:31:26.482 27278-27278/com.sinbaram.mapgo E/Filament: Panic
>     in HandleBase::HandleId filament::OpenGLDriver::allocateHandle(void *):348
>     reason: OpenGL backend handle arena is full, please increase FILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB which is currently set to 4 MiB.
> ```
> 
> I know project is under development, so wonder if it's normal.

Oh it is weird. I think it is internal problem in sceneform sdk while using flilament dependency.
There is similar [issue](https://github.com/google/filament/issues/4331 ) in filament repository.

I'll check it out today. Thanks.

**Comment by Snowapril** [comment]
@lijm1358 What device did you build on? Android studio emulator or your device?
If it was your device, please comment your device name here.

**Comment by lijm1358** [comment]
> @lijm1358 What device did you build on? Android studio emulator or your device?
> If it was your device, please comment your device name here.

I was running on my device Galaxy S21+(SM-G996N), Android 11.

**Comment by lijm1358** [comment]
btw, I was just commented out some lines `build.gradle (app)` before gradle build cause apikey.properties is not exist, and don't know how does it look like. Though api key doesn't seem to be used in this branch, but this might have affected the error above.
```
def apikeyPropertiesFile = rootProject.file("apikey.properties")
def apikeyProperties = new Properties()
apikeyProperties.load(new FileInputStream(apikeyPropertiesFile))
```

**Comment by Snowapril** [comment]
> btw, I was just commented out some lines `build.gradle (app)` before gradle build cause apikey.properties is not exist, and don't know how does it look like. Though api key doesn't seem to be used in this branch, but this might have affected the error above.
> 
> ```
> def apikeyPropertiesFile = rootProject.file("apikey.properties")
> def apikeyProperties = new Properties()
> apikeyProperties.load(new FileInputStream(apikeyPropertiesFile))
> ```

@lijm1358  Ah, that is the main cause of crash I think. For keeping secret api keys from public repository, I add ignore rule in .gitignore for keeping out of secret key file from being included in commit. 

I'll add API secret key file management guide in project README later. At now, you just need to add "apikey.properties" file to the client directory. After that, you should fill its content with key-value pair. I shared a copy of secret key files to the discord, please check it out.

**Comment by lijm1358** [comment]
> Ah, that is the main cause of crash I think. For keeping secret api keys from public repository, I add ignore rule in .gitignore for keeping out of secret key file from being included in commit.
> 
> I'll add API secret key file management guide in project README later. At now, you just need to add "apikey.properties" file to the client directory. After that, you should fill its content with key-value pair. I shared a copy of secret key files to the discord, please check it out.

@Snowapril Adding the key file not worked for me unfortunately... maybe should try another android device.

**Comment by Snowapril** [comment]
Hmm.. maybe there exists uncovered test case in this branch yet. 
I registered new issue(#4) about testing in the outside. 
At now, I think this PR need to be closed for a moment. 
After testing application and debugging your issue and then I'll reopen this PR.
Thanks for reporting.

**Comment by Snowapril** [comment]
@lijm1358 Can you check crash one more time? I fixed some stuffs

**Comment by lijm1358** [comment]
@Snowapril No crashes anymore, everything seems to be work fine.

**Comment by Snowapril** [comment]
Now looks clear and there is no more crash. I think we can merge this branch to main

**Pull request merged**
