### PR TITLE
Implement REST API interface for naver api & mapgo server

### PR DESCRIPTION
**Pull request by Snowapril**
This revision includes `rest api interface` implementation
* Naver Cloud API & Open API client
* Geocoding API interface
* Naver Search API interface (building, image)
* MapGo API client
* MapGo server Checkin, Recommendations interface
* Models for building, image, checkin and recommendation
* Unit testing for rest api connection

References
* https://square.github.io/retrofit/
* https://www.ncloud.com/
* https://developers.naver.com/docs/common/openapiguide/

### CODE REVIEW

**Review by lijm1358 — APPROVED** [review]
LGTM

**Comment by Snowapril** [comment]
@lijm1358 Thanks for reviewing !

**Comment by dldks321** [comment]
LGTM

**Review by dldks321 — COMMENTED** [review]
LGTM

**Pull request merged**
