### PR TITLE
Implement Deep Learning Recommendation system

### PR DESCRIPTION
**Pull request by lijm1358**
This revision includes
### Documents
* https://arxiv.org/abs/1708.05031
* https://arxiv.org/pdf/1606.07792
* https://developers.google.com/machine-learning/recommendation/collaborative/matrix
* https://developers.google.com/machine-learning/recommendation/collaborative/basics
* https://keras.io/guides/
* https://www.tensorflow.org/guide?hl=ko
* https://en.wikipedia.org/wiki/Haversine_formula
* https://www.selenium.dev/documentation/
* https://chromedriver.chromium.org/getting-started
* https://developer.mozilla.org/ko/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* https://developers.google.com/maps/documentation/places/web-service/search-nearby
* https://pandas.pydata.org/docs/reference/index.html#api

### CODE REVIEW

**Comment by Snowapril** [comment]
I add some commits for resolving codacy & package dependency issues.

**Comment by Snowapril** [comment]
Totally positive to me, but what is this [`location` file](https://github.com/PNU-Sinbaram/MapGo/pull/12/files#diff-221ea41ab3af5a1cf24206c5247273f64021daf956ac979b117571223b68484c) for?

**Comment by lijm1358** [comment]
> Totally positive to me, but what is this [`location` file](https://github.com/PNU-Sinbaram/MapGo/pull/12/files#diff-221ea41ab3af5a1cf24206c5247273f64021daf956ac979b117571223b68484c) for?

That file was input for searching nearby places, which means not necessary for repository(also getNearbyPlacesResult.csv)
Thanks to your comment, I removed those files. 😂

**Review by Snowapril — APPROVED** [review]
Ok. Now looks good to me! 🎉🎉

**Pull request merged**
